spring.datasource.url=jdbc:postgresql://localhost:5432/stockdb
spring.datasource.username=postgres
spring.datasource.password=Umar@2004

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

server.port=8083
finnhub.api.key=d8j6mt9r01qgth6iqi3gd8j6mt9r01qgth6iqi40