spring.datasource.url=jdbc:postgresql://ep-spring-tooth-aov6on89-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_MxKq7L2DuVEC

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=${PORT:8080}

finnhub.api.key=d8j6mt9r01qgth6iqi3gd8j6mt9r01qgth6iqi40